title: Flxibus-alg
description: naaah
theme: jekyll-theme-cayman

# Exclude files with code that breaks Jekyll
exclude: []

# Navigation
header_pages:
  - index.md
  - technical_architecture_detailed.md
